#zshrc
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
export PS1="%~ $ "
alias chrome="open -a 'Google Chrome'"
alias gh='hub browse'
alias l3='open http://localhost:3000'
alias l31='open http://localhost:3001'
alias l8='open http://localhost:8000'
alias l88='open http://localhost:8080'
alias ts='tmux source-file ~/.tmux.conf'
alias zb='open https://zenn.dev/dashboard/deploys'
alias yc='yarn create next-app -e with-tailwindcss sample-next-00000'
alias yd='yarn dev'
alias ys='yarn start'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gd='git diff'
alias gs='git status'
